### PR TITLE
Update file-browser_zh_CN.ts

### PR DESCRIPTION
**Pull request by dashinfantry**

### CODE REVIEW

**Comment by ichthyosaurus** [comment]
Thank you :). I guess I somehow did not get notified of this PR, my apologies.

**Comment by dashinfantry** [comment]
Can you update it with Chinese translation?

**Comment by ichthyosaurus** [comment]
Sure! But you marked an empty translation for "Refresh" as finished. Can you fix this before, please?

**Comment by dashinfantry** [comment]
Can your merge it now?

**Pull request merged**
