### PR TITLE
Updated Spanish language

### PR DESCRIPTION
**Pull request by carmenfdezb**

### CODE REVIEW

**Comment by carmenfdezb** [comment]
Sorry for the late answer, Spanish translate is fixed now.

**Comment by ichthyosaurus** [comment]
Thank you :). I guess I somehow did not get notified of this PR, my apologies.

**Comment by ichthyosaurus** [comment]
Hi @carmenfdezb , I hope you'll get a notification from this :). If you could give me the translation of the new string "%n item" (and "%n items") we'd have Spanish at 100%. I'm planning a new release on Friday and would love to have as many finished translations as possible :).

**Comment by carmenfdezb** [comment]
Sorry, I see your message now :/ I will check notifications in github settings.
Spanish translation is completed now.

**Comment by ichthyosaurus** [comment]
No need to apologize! Thank you very much for your efforts! :)

**Pull request merged**
